---
- name: Initial Playbook.
  hosts: all
  become: yes
  pre_tasks:
    - name: APT update.
      ansible.builtin.apt:
        update_cache: true
    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
  tasks:
    - name : Create ansible user.
      ansible.builtin.user:
        name: ansible
        shell: /bin/false
        groups: sudo
    - name: Set authorized key taken from file for ansible user.
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/tmp/sshkey01.pub') }}"
    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s