---
- name: Install docker on ubuntu OS.
  hosts: all
  become: yes
  pre_tasks:
    - name: APT update.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  tasks:
    - name: remove old.
      ansible.builtin.apt:
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        update_cache: true
    - name: Install Certificates.
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    - name: Creates /etc/apt/keyrings directory.
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Import Docker GPG key if  does not exist.
      ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
    - name: Set permissions for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'
    - name: Add Docker repository to sources.list.d
      ansible.builtin.shell: |
        echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: APT update.
      ansible.builtin.apt:
        update_cache: true
    - name: Install softwares.
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present