def mygvscript
pipeline {
    agent any
    stages{
        stage('Hello') {
            steps {
                sh '''
                ls -l
                ansible --version
                ansible-playbook --version
                ansible-galaxy --version
                '''
            }
        }
        stage('Run Playbooks') {
            steps {
                dir('./ansible_playbooks') {
                    sh 'ls -l'
                    sh 'ansible-playbook pb01.yml'
                }
            }
        }
    }
}
 